version: '3'

services:
  postgres_db:
    image: postgres:14-alpine
    volumes:
      - weather_volume:/var/lib/postgresql/data
      - /src/main/resources/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      PGUSER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "docker_app" ]
      interval: 5s
      timeout: 5s
      retries: 3

  weather:
    image: timmawv/weather-app
    env_file:
      - credentials.env
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "--fail", "localhost:8080/WeatherApp-1.0/test-back" ]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  weather_volume: