CREATE TABLE IF NOT EXISTS Users
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login    VARCHAR UNIQUE NOT NULL,
    password VARCHAR        NOT NULL
);

CREATE TABLE IF NOT EXISTS Locations
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR NOT NULL,
    latitude  DECIMAL NOT NULL,
    longitude DECIMAL NOT NULL,
    user_id   INT     NOT NULL REFERENCES Users (id) ON DELETE CASCADE,
    UNIQUE (latitude, longitude, user_id)
);

CREATE TABLE IF NOT EXISTS Sessions
(
    id         VARCHAR PRIMARY KEY,
    user_id    INT       NOT NULL REFERENCES Users (id) ON DELETE CASCADE,
    expires_at timestamp NOT NULL
);

CREATE INDEX idx_user_session ON Sessions (expires_at);

INSERT INTO Users(login, password)
VALUES ('timur', '$2a$10$M55sGHCwyjyd6AuGcp0HKuu.LOjyA9kAIaPGIXy7mUQw.ByskwCjC'),
       ('dima', '$2a$10$M55sGHCwyjyd6AuGcp0HKuu.LOjyA9kAIaPGIXy7mUQw.ByskwCjC');