CREATE TABLE Users
(
    ID       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Login    VARCHAR UNIQUE,
    Password VARCHAR
);

CREATE TABLE Locations
(
    ID        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Name      VARCHAR,
    UserId    INT,
    Latitude  DECIMAL,
    Longitude DECIMAL,
    FOREIGN KEY (UserId) REFERENCES Users (ID)
);

CREATE TABLE Sessions
(
    ID VARCHAR,
    UserId INT,
    ExpiresAt DATE,
    FOREIGN KEY (UserId) REFERENCES Users(ID)
);